title: Chinese Muslim RAG Corpus
description: A highly structured corpus of Islamic articles.
url: "https://salaamalykum.github.io"
baseurl: "/Chinese-Muslim"
theme: minima
lastmod: "2026-06-13T14:45:34Z"
